less tests

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -697,7 +697,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
+        os: [ubuntu-latest, windows-latest]
         python: ['3.7']
     steps:
       - name: Checkout
@@ -767,73 +767,73 @@ jobs:
           path: .nyc_output
           retention-days: 1
 
-  coverage:
-    name: Coverage reports upload
-    runs-on: ubuntu-latest
-    if: "(success() || failure()) && !contains(github.ref, 'refs/heads/release')"
-    needs: [ts_tests, vscodeTests, smoke-tests]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+#   coverage:
+#     name: Coverage reports upload
+#     runs-on: ubuntu-latest
+#     if: "(success() || failure()) && !contains(github.ref, 'refs/heads/release')"
+#     needs: [ts_tests, vscodeTests, smoke-tests]
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v2
 
-      - name: Install Node
-        uses: actions/setup-node@v2.4.1
-        with:
-          node-version: ${{env.NODE_VERSION}}
+#       - name: Install Node
+#         uses: actions/setup-node@v2.4.1
+#         with:
+#           node-version: ${{env.NODE_VERSION}}
 
-      - name: Install dependencies (npm ci)
-        run: npm ci --prefer-offline
+#       - name: Install dependencies (npm ci)
+#         run: npm ci --prefer-offline
 
-      - name: Cache compiled TS files
-        id: out-cache
-        uses: actions/cache@v2.1.4
-        with:
-          path: ./out
-          key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}
+#       - name: Cache compiled TS files
+#         id: out-cache
+#         uses: actions/cache@v2.1.4
+#         with:
+#           path: ./out
+#           key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}
 
-      - name: Compile if not cached
-        run: npx gulp prePublishNonBundle
-        env:
-          CI_JUPYTER_FAST_COMPILATION: 'true'
+#       - name: Compile if not cached
+#         run: npx gulp prePublishNonBundle
+#         env:
+#           CI_JUPYTER_FAST_COMPILATION: 'true'
 
-      # It isn't possible to specify a regex for artifact names, so we have to download each artifact manually.
-      # The name pattern is ${{runner.os}}-${{env.COVERAGE_REPORTS}}, and possible values for runner.os are `Linux`, `Windows`, or `macOS`.
-      # See https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#runner-context
-      - name: Download Ubuntu test coverage artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
-          path: ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
+#       # It isn't possible to specify a regex for artifact names, so we have to download each artifact manually.
+#       # The name pattern is ${{runner.os}}-${{env.COVERAGE_REPORTS}}, and possible values for runner.os are `Linux`, `Windows`, or `macOS`.
+#       # See https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#runner-context
+#       - name: Download Ubuntu test coverage artifacts
+#         uses: actions/download-artifact@v2
+#         with:
+#           name: ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
+#           path: ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
 
-      - name: Extract Ubuntu coverage artifacts to ./nyc_output
-        run: |
-          pwd
-          mkdir .nyc_output
-          mv ${{runner.os}}-${{ env.COVERAGE_REPORTS }}/* .nyc_output
-          rm -r ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
+#       - name: Extract Ubuntu coverage artifacts to ./nyc_output
+#         run: |
+#           pwd
+#           mkdir .nyc_output
+#           mv ${{runner.os}}-${{ env.COVERAGE_REPORTS }}/* .nyc_output
+#           rm -r ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
 
-      - name: Merge coverage reports
-        run: |
-          pwd
-          npx nyc merge ./.nyc_output
-          rm -r .nyc_output
-          mkdir .nyc_output
-          mv coverage.json ./.nyc_output
-        continue-on-error: true
+#       - name: Merge coverage reports
+#         run: |
+#           pwd
+#           npx nyc merge ./.nyc_output
+#           rm -r .nyc_output
+#           mkdir .nyc_output
+#           mv coverage.json ./.nyc_output
+#         continue-on-error: true
 
-      - name: Generate coverage reports
-        run: npm run test:cover:report
-        continue-on-error: true
+#       - name: Generate coverage reports
+#         run: npm run test:cover:report
+#         continue-on-error: true
 
-      - name: Upload coverage to codecov
-        uses: codecov/codecov-action@v1
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          file: ./coverage/cobertura-coverage.xml
-          path_to_write_report: ./coverage/codecov_report.txt
-      # Alternative method for uploading
-      # - name: Upload coverage to codecov
-      #  run: bash <(curl -s https://codecov.io/bash) -f ./coverage/cobertura-coverage.xml -v
+#       - name: Upload coverage to codecov
+#         uses: codecov/codecov-action@v1
+#         with:
+#           token: ${{ secrets.CODECOV_TOKEN }}
+#           file: ./coverage/cobertura-coverage.xml
+#           path_to_write_report: ./coverage/codecov_report.txt
+#       # Alternative method for uploading
+#       # - name: Upload coverage to codecov
+#       #  run: bash <(curl -s https://codecov.io/bash) -f ./coverage/cobertura-coverage.xml -v
 
   release:
     name: Release
